### ISSUE TITLE
Unused way of initializing a covobs

### ISSUE THREAD

**Issue by fjosw** [fjosw/pyerrors#25]
In the tests we are running the following line is never called
https://github.com/fjosw/pyerrors/blob/fc25ec692910a0c838b7b47ba3e49655150fd961/pyerrors/obs.py#L100
as all covobs seem to be initialized via `cov_Obs` or `derived_observable` where the `covobs` attribute is set manually. Can this line and the accompanying parameter be removed?

**Comment by s-kuberski** [comment]
That is true, currently this feature is not used. I intended to use it to initialize an Obs with covobs, but this is now done differently. in cov_Obs.

In general, we could put an underscore in front of covobs, as well. 

Probably
https://github.com/fjosw/pyerrors/blob/fc25ec692910a0c838b7b47ba3e49655150fd961/pyerrors/obs.py#L1643-L1644
could be deleted as well, since I only needed this to get the workaround for non-Obs in derived_observables running again. This would need a check, if idl or shape are referenced anywhere else.

BTW: Is the dummy contribution of 
https://github.com/fjosw/pyerrors/blob/fc25ec692910a0c838b7b47ba3e49655150fd961/pyerrors/obs.py#L1061
included in the derived observable, or do you exclude the name (and the entry in covobs) anywhere?

**Comment by s-kuberski** [comment]
I can take care of deleting the unnecessary stuff.

I don't really like to pollution, I have to say (but currently, I don't use the workaround anyways...). One could just construct allcov before adding the dummy contribution (at the same time, one can ensure that the dummy name is not present in allcov) and just ignore the contribution afterwards.
