### ISSUE TITLE
Redundancies in Corr class

### ISSUE THREAD

**Issue by fjosw** [fjosw/pyerrors#50]
When going over the `Corr` class I noticed that
- [x] The method `projected` seems to be able to do everything the method `smearing` does. Can we simply remove `smearing`?
- [ ] The method `Eigenvalue` is undocumented and seems to follow a different workflow than the `GEVP` method. Is this method still needed or can it be removed or refactored?
- [x] `smearing_symmetric` seems to be only used within `Eigenvalue`.
- [x] The method `sum` is undocumented and not called within any other methods. Is this method still needed or can it be removed or refactored?

Can you take a look at this @JanNeuendorf ?

**Comment by JanNeuendorf** [comment]
1. It is true, that projected can do everything smearing does. But it is a bit awkward to use projected to get a single sub-correlator. I would use it in there fore debugging and i plan to add an option to not just pick a single smearing but a sub-matrix 
2. This is true, i left it in there for testing only. It can go, if you want. But i think it is nice to have the simple function for a quick comparison.
3. smearing symmetric can (and should) be used whenever a correlator is symmetric under flipping the source and sink. I just used it in the Eigenvalue method, because the cholesky decomposition breaks with non-symmetric matrices. 
4. Yes, sum was just there for a test. It should be deleted.

**Comment by fjosw** [comment]
Thanks for your assessment.
- I removed the `sum` method in commit 07ca32f1669435adb37ddf47c3015adda420e2da as you suggested. 
- I agree that we should keep `smearing_symmetric`. I am not 100% happy with the name `smearing` as the matrices used for the GEVP do not necessarily only contain different smearing levels but could contain other correlation functions of operators coupling to the same quantum numbers. Maybe we can discuss this in our next call.
- For both `smearing` and `Eigenvalue` I see two options:
    - We could keep them in the namespace of the Corr class. I would then suggest that `smearing` internally calls `projected` with the appropriate arguments to improve future maintenance. `Eigenavalue` is still lacking a docstring.
    - Alternatively we could remove the two functions from the module, move them to the tests and use them to independently verify their counterparts.

**Comment by fjosw** [comment]
That sounds very reasonable. So you would propose to change the `Eigenvalue` method to intrinsically call something like `C.projected(C.GEVP())`? Maybe @s-kuberski can assess whether that would work also for the applications he has in mind.

**Comment by JanNeuendorf** [comment]
Yes, i can not come up with an example, where this would not work.

**Comment by s-kuberski** [comment]
I'll try to check this...
