### ISSUE TITLE
gamma method in corr routines

### ISSUE THREAD

**Issue by JanNeuendorf** [fjosw/pyerrors#69]
We need to add the gamma method to certain functions, 
because something like:
<code>corr.m_eff().some_func().show() </code>
would stop working otherwise.

**Comment by s-kuberski** [comment]
It should work, but it would not show the errors, I assume. The question is, whether such one-liner has to work, when this means that one has to call the gamma method without the user knowing it/ been able to prevent this.

**Comment by fjosw** [comment]
I think `corr.m_eff().some_func().show()` should still work just without displaying any y-errors for the individual data points. I see the convenience of this one-liner but I think having to call the `gamma_method` explicitly leads to cleaner workflows as one should always manually monitor the autocorrelation function and the chosen window and adjust the parameters of the `gamma_method` accordingly (there can be unpleasant surprises otherwise). The problem with implicit calls to the `gamma_method` is that manually chosen values for say `S` would be overwritten (which the user might not expect). 

One thing we could think about is giving the `show` method an additional parameter which triggers running the `gamma_method` (with standard parameters but explicitly authorized by the user). This would alter your one-liner to
```python
corr.m_eff().some_func().show(run_the_gamma_method_before_plotting=True) 
```
or something like that (suggestions for a short but meaningful parameter name are appreciated).

**Comment by JanNeuendorf** [comment]
I think you are right. The show method is really the only method that really needs to have this. I suggest to call it auto_gamma to imply that it uses the default parameters and to have it default to true, so one does not have to set it for every <code>.show</code>.

**Comment by fjosw** [comment]
`auto_gamma` sounds like a good solution, I can take care of that. I would prefer to default the parameter to `False`. Otherwise the following could happen
```python
corr.gamma_method(S=3.0)
corr.show()
print(corr[0].S)
> {'my_ensemble': 2.0}
```
which could be confusing to a user unfamiliar with the history of this.

We could also introduce a `apply_gamma` method if that is useful for you. Although I have to say that `corr.apply_gamma().some_func_needing_errors().m_eff().apply_gamma().show()` is not very readable :sweat_smile:
